default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # sslmode: require

#DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
  # 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
# psql -h database-1.cbtbof2lkjhb.ap-southeast-1.rds.amazonaws.com -p 5432 -U postgres -d lmcation_project_production
# psql --host=lmc-data.cbtbof2lkjhb.ap-southeast-1.rds.amazonaws.com --port=5432 --user=lmcation_project
# psql -h lmc-data.cbtbof2lkjhb.ap-southeast-1.rds.amazonaws.com
# psql "host=lmc-data.cbtbof2lkjhb.ap-southeast-1.rds.amazonaws.com port=5432 sslmode=verify-full sslrootcert=/sample_dir/rds-combined-ca-bundle.pem dbname=DBName user=jane_doe password=$PGPASSWORD"
# CREATE ROLE cam WITH PASSWORD 'cam123' CREATEDB CREATEROLE LOGIN;
# psql -h lmc-data.cbtbof2lkjhb.ap-southeast-1.rds.amazonaws.com -U lmcation-project -d lmc-data
# psql -h lmc-data.cbtbof2lkjhb.ap-southeast-1.rds.amazonaws.com -p 5432 "sslmode=verify-full sslrootcert=rds-ca-2019-root.pem dbname=aurora_pg_ssl user=webit"