# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d000038cb70d25d1a27f0d20cdeb49ee434203df1cdcc03383e8f56abc4a0a68e5bd19a696a4713f2dc2902ee22e166904d815be72c7dd5f4794ac09739a1217
  best_seller_link: best_wmuq3g.jpg
  promotion_link: promo_xketut.jpg
  new_arrival_link: arrival_l7ceqa.jpg
  inspiration_link: v1622132329/inspiration_sm.jpg
  empowerment_link: v1622132455/empowerment_sm.jpg
  gmail_email: no-reply@lmcation.com
  gmail_password: tlxnvgsozyceiyng

test:
  secret_key_base: 676dea761bfc2d074a69bc3acb8cd63a8c48304ce92d83651c945dfd91b1be5e06f8209e58d28c5c97075c6696f0109bb96240f1367db7ea1e9bc49f0b54c20e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  best_seller_link: <%= ENV["BEST_SELLER_LINK"] %>
  promotion_link: <%= ENV["PROMOTION_LINK"] %>
  new_arrival_link: <%= ENV["NEW_ARRIVAL_LINK"] %>
  inspiration_link: <%= ENV["INSPIRATION_LINK"] %>
  empowerment_link: <%= ENV["EMPOWERMENT_LINK"] %>
  gmail_email: <%= ENV["GMAIL_EMAIL"] %>
  gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
  bucket: <%= ENV["BUCKET"] %>
  access_key_id: <%= ENV["ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["SECRET_ACCESS_KEY"] %>
  s3_region: <%= ENV["S3_REGION"] %>